Add annotation
eneiluj/integration_dropbox pull request #10
Opened 2021-05-18 12:31 UTC by vitormattos

Hi @eneiluj ,
I'm reviewing your app's code. I want to improve performance and parallelize the download of Dropbox files.
Is it okay to send separate pull requests to make code review easy?

2021-05-18 14:30 UTC, eneiluj commented
Hi @vitormattos,

As long as the changes don't mix multiple different things/topics, you can make big PRs, i don't mind.
Do you want to add stuff to this PR or can I merge it right now?

2021-05-18 14:32 UTC, eneiluj commented
And by the way, as Dropbox most likely sends faster than everybody can receive, I don't feel it's necessary to parallelize file download as you're still going to get stuck at your connection max speed.

2021-05-18 16:20 UTC, vitormattos commented
For now nothing to add to it.

Because the app is without unit tests, I'm doing manual tests. I think it's safer to go for smaller parts so as not to get too complex when doing the review.

2021-05-18 16:31 UTC, vitormattos commented
I need to transfer more than 600 GB from Dropbox to the Nextcloud and for some reason the job is dying without logs after about 60 GB transferred.

Importing files has other processes besides downloading, for example IO. When the import is done in a queue and for many files, the time increases.

The goal is to parallel a poll of up to 5 requests so that, while a download is being made, a response promise from another download is being processed.

2021-05-18 17:04 UTC, vitormattos commented
Just in time, I can put this pull request as a draft and add everything to it. Finally, you do one last review.
Do you prefer it this way?

Now that I recognize you, hi @eneiluj !!!

2021-05-24 14:56 UTC, vitormattos commented
Hi @eneiluj ,
I made some refactors and I'm testing with the import of 600Gb, it is without problems.
I suggest you do the code review by the sequence of commits.

2021-05-31 10:17 UTC, eneiluj requested changes
Thanks for this PR. A few things to adjust and let's merge it.

2021-05-31 10:17 UTC, eneiluj commented on lib/Service/DropboxStorageAPIService.php
> +		}
```suggestion
		try {
			if ($saveFolder->nodeExists($fileName)) {
				return null;
			}
		} catch (ForbiddenException $e) {
			return null;
		}
```
In some cases, this is needed. For example when importing files named `.htaccess`.

2021-05-31 11:16 UTC, vitormattos commented on lib/Service/DropboxStorageAPIService.php
> +							string $userId, array $fileItem, Node $topFolder): ?int {
It’s good to have unit tests to document these exception scenarios.

I did tests with files over 1024Mb. An error occurs that I have not been able to resolve. The error occurs with the code before and after this my PR. If you want I can register an issue with the log.

2021-05-31 11:17 UTC, eneiluj commented on lib/Service/DropboxStorageAPIService.php
> +							string $userId, array $fileItem, Node $topFolder): ?int {
> If you want I can register an issue with the log.

Yes sure :grin:.

2021-05-31 11:18 UTC, eneiluj commented
You forgot to import `OCP\Files\ForbiddenException` :wink:.

2021-05-31 11:25 UTC, vitormattos commented
@eneiluj done.

2021-05-31 11:38 UTC, eneiluj approved these changes
Thanks!

2021-05-31 11:39 UTC, merged